#!/usr/bin/env python

def descend(subdirs):
	
	if type(subdirs) is str:
		subdirs += '/SConstruct'
	else:
		for i in range( 0, subdirs.__len__(), 1 ):
			subdirs[i] += '/SConstruct'
		
	SConscript(subdirs)

env = Environment()
target = 'llHomeworld'


game_descriptions = ["Building original binary for Homeworld", "Building Raiders Retreat binary for Homeworld", "Building Demo binary for Homeworld"]
game_types = ["HW_GAME_HOMEWORLD", "HW_GAME_RAIDER_RETREAT", "HW_GAME_DEMO"]
game_index = 0

build_descriptions = ["Building debug binary for Homeworld", "Building distribution binary for Homeworld"]
build_types = ["HW_BUILD_FOR_DEBUGGING", "HW_BUILD_FOR_DISTRIBUTION"]
build_index = 0

env.Replace(CC = "llvm-gcc")
env.Replace(LINK = "llvm-ld")
env.Append(CCFLAGS="-emit-llvm -c")
print game_descriptions[game_index]
env.Append(CPPDEFINES=game_types[game_index])

print build_descriptions[build_index]
env.Append(CPPDEFINES=build_types[build_index])

env.Append(CPPDEFINES=HW_ENABLE_MOVIES)

#print env.items()

#env.Program(target = target, source = ["helloworld.c"])

Export('env', 'descend')
descend('..')



