#!/usr/bin/env python
# Import everything in global
Import('*')

sources = []
sources.append(Glob('*.cpp'))
sources.append(Glob('emul/*.cpp'))
sources.append(Glob('../GLES1/emul/*.cpp'))
sources.append(Glob('../GLES/*.cpp'))

addLibrary("GLES2", sources)

