#!/usr/bin/env python
# Import everything in global
import os
Import('*')

generated = []
generated.append(descend("SinglePlayer"))
#generated.append(descend("Tutorials"))

directory = "Generated"

def compileLevels(path):
	levels = Glob(directory + "/" + path)
	for levelFile in levels:
		basename = levelFile.name
		names = os.path.splitext(basename)
		filename = names[0]
		
		executable = ""
		
		kasTool = tools[0]
		
		for node in kasTool:
			executable += node.__str__()
			
		rootDir = Dir('#')

		relDirectory = os.path.relpath(directory, rootDir.abspath)
			
		# Use relative paths to kas2c binary
		executable = os.path.relpath(executable, directory)
		
		# Use relative paths for output
		relOutputPath = os.path.relpath(os.path.splitext(levelFile.abspath)[0], rootDir.abspath)
		
		# Use relative paths for input
		relInputPath = os.path.relpath(levelFile.abspath, rootDir.abspath)
		
		cmd = "chdir " + relDirectory + " && " + executable + " " + filename + ".kp " + filename + ".c " + filename + ".h " + filename + ".func.c"

		genf = directory + "/" + filename
		command = env.Command([genf + ".c", genf + ".h", genf + ".func.c"], genf + ".kp", cmd)
		Depends(command, kasTool)

compileLevels("Mission*.kp")
compileLevels("Tutorial*.kp")

descend(directory)

