#!/usr/bin/env python
# Import everything in global
Import('*')

sources = Glob("*.c")

notincl = ["debugwnd.c", "wave.c", "win32glue.c", "prim3d.c", "render.c"]

for nifile in notincl:
	for s in sources:
		if s.name == nifile:
			sources.remove(s)

hwlibrary("SDL", sources)

