#!/usr/bin/env python
# Import everything in global
Import('*')

sources = Glob("*.c")

ignored = ["debugwnd.c", "wave.c", "win32glue.c", "TitanInterfaceC.stub.c"]

addLibrary("SDL", sources, ignored)

