#!/usr/bin/env python
# Import everything in global
Import('*')

sources = Glob("*.c")

ignored = ["debugwnd.c", "wave.c", "win32glue.c", "prim3d.c", "TitanInterfaceC.stub.c"]

hwlibrary("SDL", sources, ignored)

