#!/usr/bin/env python
# Import everything in global
Import('*')

# TODO: Do not hardcode this directory
ABSPATH = "#android"
env = getOptionEnv()
arch = []
if is_arm():
    arch.append("armeabi")
elif is_armv7():
    arch.append("armeabi-v7a")
elif is_32():
    arch.append("x86")

env.Tool("android",
         project_root=env.Dir(ABSPATH),
         chdir=env.Dir('.').abspath,
         arch=arch,
         is_debug=is_debug(),
         toolchain_version=(4,6,3))

descend('jni')

addProgram(
    target = "home_android",
    source = "jni/game/homeworld.c",
    LIBS    = ["Game", "Ships"],
    LIBPATH = ["jni/game/Game", "jni", "jni/game/Ships"]
)