#!/usr/bin/env python
# Import everything in global
Import('*')

flags = env["CCFLAGS"]
path = env["CPPPATH"]

env = Environment()
env["CCFLAGS"] = flags
env.MergeFlags("CCFLAGS", ["-g", "-O2", "-malign-double"])
env.MergeFlags("CPPDEFINES", ["_X86", {"_GNU_SOURCE" : "1"}, "_REENTRANT"])
env["CPPPATH"] = path
env.Replace(YACCFLAGS = "-y -d")
env.Replace(LEXFLAGS = "-i")

tool = env.Program(
	target = 'kas2c',
	source = ["kas2c.c", "lexer.l", "parser.y"],
	LIBS="libl.a"
)

tools.append(tool)

