#!/usr/bin/env python
# Import everything in global
Import('*')

flags = list(env["CCFLAGS"])
flags.remove("-S")

kenv = Environment()
kenv["CCFLAGS"] = flags
kenv.MergeFlags("CCFLAGS", ["-g", "-O2", "-malign-double"])
kenv.MergeFlags("CPPDEFINES", ["_X86"])
kenv["CPPPATH"] = includedirs
kenv.ParseConfig('sdl-config --cflags --libs')
kenv.Replace(YACCFLAGS = "-y -d")
kenv.Replace(LEXFLAGS = "-i")

#print kenv["CC"]

tool = kenv.Program(
	target = 'kas2c',
	source = ["kas2c.c", "lexer.l", "parser.y"],
	LIBS="libl.a"
)

tools.append(tool)

