#!/usr/bin/env python
# Import everything in global
Import('*')

includedirs = [
	'.',
	"ThirdParty/CRC",
	"ThirdParty/JPG",
	"ThirdParty/LZSS",
	"Game",
	"Ships",
	"ThirdParty/Titan",
	"SDL"
]

env = getOptionEnv()

# We need to use the abspath because for some dumb reason
# SCons fucks up otherwise
for i in range(0, len(includedirs), 1):
	includedirs[i] = env.Dir(includedirs[i]).abspath

env.AppendUnique(CPPPATH=includedirs)

#TODO: Ugly hack - fix later
if not is_llvm():
	env.ParseConfig('sdl-config --cflags --libs')

modules = ['Missions', 'Game', 'ThirdParty', 'SDL', 'Ships']

if is_gles2():
	modules.append("GLES2")

descend(modules)

